// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TruckApi.Infrastructure.Database;

#nullable disable

namespace TruckApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528130036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Checklist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex(new[] { "MachineId", "StartedAt" }, "checklists_machine_date_idx");

                    b.HasIndex(new[] { "MachineId" }, "checklists_machine_id_idx");

                    b.HasIndex(new[] { "OperatorId" }, "checklists_operator_id_idx");

                    b.ToTable("checklists");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistItemResponse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChecklistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checklist_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TemplateItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_item_id");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("checklist_item_responses");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MachineType")
                        .HasColumnType("text")
                        .HasColumnName("machine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("checklist_templates");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistTemplateItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("checklist_template_items");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Geofence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Polygon")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("polygon");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "geofences_company_id_idx");

                    b.ToTable("geofences");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.GeofenceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("GeofenceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geofence_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GeofenceId" }, "geofence_events_geofence_id_idx");

                    b.HasIndex(new[] { "MachineId" }, "geofence_events_machine_id_idx");

                    b.HasIndex(new[] { "MachineId", "OccurredAt" }, "geofence_events_machine_time_idx");

                    b.ToTable("geofence_events");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.HourRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<decimal?>("HourmeterEnd")
                        .HasColumnType("numeric")
                        .HasColumnName("hourmeter_end");

                    b.Property<decimal?>("HourmeterStart")
                        .HasColumnType("numeric")
                        .HasColumnName("hourmeter_start");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("numeric")
                        .HasColumnName("total_hours");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MachineId", "Date" }, "hour_records_machine_date_idx");

                    b.HasIndex(new[] { "MachineId" }, "hour_records_machine_id_idx");

                    b.HasIndex(new[] { "OperatorId" }, "hour_records_operator_id_idx");

                    b.ToTable("hour_records");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Machine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentHourmeter")
                        .HasColumnType("numeric")
                        .HasColumnName("current_hourmeter");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .HasColumnType("text")
                        .HasColumnName("plate");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "CompanyId" }, "machines_company_id_idx");

                    b.HasIndex(new[] { "Status" }, "machines_status_idx");

                    b.ToTable("machines");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.MachineLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Heading")
                        .HasColumnType("numeric")
                        .HasColumnName("heading");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<decimal?>("Speed")
                        .HasColumnType("numeric")
                        .HasColumnName("speed");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MachineId", "RecordedAt" }, "machine_locations_machine_time_idx");

                    b.ToTable("machine_locations");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.MaintenanceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("HourmeterAtService")
                        .HasColumnType("numeric")
                        .HasColumnName("hourmeter_at_service");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<decimal?>("NextServiceHourmeter")
                        .HasColumnType("numeric")
                        .HasColumnName("next_service_hourmeter");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("PerformedById")
                        .HasColumnType("text")
                        .HasColumnName("performed_by_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex(new[] { "MachineId" }, "maintenance_records_machine_id_idx");

                    b.ToTable("maintenance_records");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedTermsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_terms_at");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Picture")
                        .HasColumnType("text")
                        .HasColumnName("picture");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.HasIndex("Whatsapp")
                        .IsUnique();

                    b.HasIndex(new[] { "CompanyId" }, "users_company_id_idx");

                    b.HasIndex(new[] { "CompanyId", "Role" }, "users_company_id_role_idx");

                    b.HasIndex(new[] { "IsActive" }, "users_is_active_idx");

                    b.HasIndex(new[] { "Role" }, "users_role_idx");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Checklist", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Machine", "Machine")
                        .WithMany("Checklists")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckApi.Infrastructure.Database.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckApi.Infrastructure.Database.Entities.ChecklistTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistItemResponse", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Checklist", "Checklist")
                        .WithMany("ItemResponses")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckApi.Infrastructure.Database.Entities.ChecklistTemplateItem", "TemplateItem")
                        .WithMany()
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Company", "Company")
                        .WithMany("ChecklistTemplates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistTemplateItem", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.ChecklistTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Geofence", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Company", "Company")
                        .WithMany("Geofences")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.GeofenceEvent", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Geofence", "Geofence")
                        .WithMany("Events")
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Geofence");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.HourRecord", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Machine", "Machine")
                        .WithMany("HourRecords")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckApi.Infrastructure.Database.Entities.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Machine", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Company", "Company")
                        .WithMany("Machines")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.MachineLocation", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Machine", "Machine")
                        .WithMany("Locations")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Machine", "Machine")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckApi.Infrastructure.Database.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Machine");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.User", b =>
                {
                    b.HasOne("TruckApi.Infrastructure.Database.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Checklist", b =>
                {
                    b.Navigation("ItemResponses");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Company", b =>
                {
                    b.Navigation("ChecklistTemplates");

                    b.Navigation("Geofences");

                    b.Navigation("Machines");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Geofence", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TruckApi.Infrastructure.Database.Entities.Machine", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("HourRecords");

                    b.Navigation("Locations");

                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
